---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: automation-seed
  labels:
    app: automation-seed
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: automation-seed
  template:
    metadata:
      labels:
        app: automation-seed
        version: '0'
    spec:
      containers:
      - name: automation-seed
        image: atomist/automation-seed-ts:0.12.0
        imagePullPolicy: IfNotPresent
        env:
        - name: ATOMIST_CONFIG_PATH
          value: /opt/atm/client.config.json
        ports:
        - name: http
          containerPort: 2866
          protocol: TCP
        livenessProbe:
          httpGet:
            path: "/health"
            port: 2866
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 3
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: "/health"
            port: 2866
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 3
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 384Mi
        volumeMounts:
        - name: automation
          mountPath: /opt/atm
          readOnly: true
      volumes:
      - name: automation
        secret:
          secretName: automation
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
